import type {Config} from "prettier";
export default {
	arrowParens: `always`,
	bracketSameLine: true,
	bracketSpacing: false,
	endOfLine: `lf`,
	experimentalOperatorPosition: `start`,
	experimentalTernaries: true,
	htmlWhitespaceSensitivity: `strict`,
	objectWrap: `collapse`,
	overrides: [],
	plugins: [`prettier-plugin-svelte`],
	printWidth: 80,
	quoteProps: `preserve`,
	semi: true,
	singleAttributePerLine: true,
	singleQuote: false,
	svelteAllowShorthand: false,
	svelteIndentScriptAndStyle: true,
	svelteSortOrder: `options-scripts-markup-styles`,
	svelteStrictMode: true,
	trailingComma: `all`,
	useTabs: true,
} as const satisfies Config;
