import type {TagOfDockerImageOfDebianOfConfigurationOfEnvironmentOfTesting} from "./tag/TagOfDockerImageOfDebianOfConfigurationOfEnvironmentOfTesting.ts";
export type DockerImageOfDebianOfConfigurationOfEnvironmentOfTesting = {
	readonly tag: TagOfDockerImageOfDebianOfConfigurationOfEnvironmentOfTesting;
};
