import type {
	WithNodeAdapterConfigurationOfEnvironmentOfBuilding,
	WithoutAdapterConfigurationOfEnvironmentOfBuilding,
	WithStaticAdapterConfigurationOfEnvironmentOfBuilding,
} from "../implementations/index.ts";
export type SupportedConfigurationOfEnvironmentOfBuilding =
	| WithNodeAdapterConfigurationOfEnvironmentOfBuilding
	| WithoutAdapterConfigurationOfEnvironmentOfBuilding
	| WithStaticAdapterConfigurationOfEnvironmentOfBuilding;
